documentation:
  - any: ['docs/**/*', '*.md']

workflow:
  - any:
      ['.github/**/*', '.husky/**/*', '.vscode/**/*', '.github/workflow/**/*']

# Chore
'chore':
  - dependencies/**/*
  - public/**/*
  - package.json
  - '*'

'BREAKING CHANGES':
  - src/assets/**/*
