'📝documentation':
  - README.md
  - CONTRIBUTING.md
  - '*.md'

# Chore
'chore':
  - dependencies/**/*
  - public/**/*
  - package.json
  - .github/**/*
  - .vscode/**/*
  - '*'

'⚠️BREAKING CHANGES!!!':
  - src/assets/**/*
